import type { Model } from '@/types/models';
import type { ReasoningParameters } from '@/types/reasoning';

export const MODELS: { [key: string]: { [key: string]: Model } } = {
  anthropic: {
    CLAUDE_SONNET_4_5:{
      id: 'claude-sonnet-4-5-20250929',
      name: 'Claude Sonnet 4.5',
      contextWindow: 200000,
      maxTokens: 64000,
      multimodal: true,
      supportFunctionCalling: true,
      supportsReasoning: false,
    },
    CLAUDE_OPUS_4_1: {
      id: 'claude-opus-4-1-20250805',
      name: 'Claude Opus 4.1',
      contextWindow: 200000,
      maxTokens: 32000,
      multimodal: true,
      supportFunctionCalling: true,
      supportsReasoning: false,
    },
    CLAUDE_SONNET_4_5_THINKING:{
      id: 'claude-sonnet-4-5-20250929-thinking',
      name: 'Claude Sonnet 4.5 (with Thinking)',
      contextWindow: 200000,
      maxTokens: 64000,
      multimodal: true,
      supportFunctionCalling: true,
      supportsReasoning: true,
      reasoningParameters: {
        type: 'budget',
        budgetTokenLimit: 31999,
        budgetTokens: 4096,
      } as ReasoningParameters,
    },
    CLAUDE_OPUS_4_1_THINKING: {
      id: 'claude-opus-4-1-20250805-thinking',
      name: 'Claude Opus 4.1 (with Thinking)',
      contextWindow: 200000,
      maxTokens: 32000,
      multimodal: true,
      supportFunctionCalling: true,
      supportsReasoning: true,
      reasoningParameters: {
        type: 'budget',
        budgetTokenLimit: 31999,
        budgetTokens: 4096,
      },
    },
    CLAUDE_HAIKU_4_5: {
      id: 'claude-haiku-4-5-20251001',
      name: 'Claude Haiku 4.5',
      contextWindow: 200000,
      maxTokens: 64000,
      multimodal: true,
      supportFunctionCalling: true,
      supportsReasoning: false,
    },
    CLAUDE_HAIKU_4_5_THINKING: {
      id: 'claude-haiku-4-5-20251001-thinking',
      name: 'Claude Haiku 4.5 (with Thinking)',
      contextWindow: 200000,
      maxTokens: 64000,
      multimodal: true,
      supportFunctionCalling: true,
      supportsReasoning: true,
      reasoningParameters: {
        type: 'budget',
        budgetTokenLimit: 31999,
        budgetTokens: 4096,
      },
    },
  },
  openai: {
    OPENAI_GPT_5: {
      id: 'gpt-5',
      name: 'GPT-5',
      contextWindow: 400000,
      maxTokens: 128000,
      multimodal: true,
      supportsReasoning: true,
      reasoningParameters: {
        type: 'effort',
        effort: 'medium',
      },
      unsupportsTemperature: true,
      supportFunctionCalling: true,
    },
    OPENAI_GPT_5_MINI: {
      id: 'gpt-5-mini',
      name: 'GPT-5 Mini',
      contextWindow: 400000,
      maxTokens: 128000,
      multimodal: true,
      supportsReasoning: true,
      reasoningParameters: {
        type: 'effort',
        effort: 'medium',
      },
      unsupportsTemperature: true,
      supportFunctionCalling: true,
    },
    OPENAI_GPT_5_NANO: {
      id: 'gpt-5-nano',
      name: 'GPT-5 nano',
      contextWindow: 400000,
      maxTokens: 128000,
      multimodal: true,
      supportsReasoning: true,
      reasoningParameters: {
        type: 'effort',
        effort: 'medium',
      },
      unsupportsTemperature: true,
      supportFunctionCalling: true,
    },
    OPENAI_O3: {
      id: 'o3',
      name: 'o3',
      contextWindow: 200000,
      maxTokens: 100000,
      multimodal: true,
      supportsReasoning: true,
      reasoningParameters: {
        type: 'effort',
        effort: 'medium',
      },
      unsupportsTemperature: true,
      supportFunctionCalling: true,
    },
    OPENAI_O4_MINI: {
      id: 'o4-mini',
      name: 'o4-mini',
      contextWindow: 200000,
      maxTokens: 100000,
      multimodal: true,
      supportsReasoning: true,
      reasoningParameters: {
        type: 'effort',
        effort: 'medium',
      },
      unsupportsTemperature: true,
      supportFunctionCalling: true,
    },
    OPENAI_CHATGPT_5: {
      id: 'gpt-5-chat-latest',
      name: 'GPT-5 Chat',
      contextWindow: 128000,
      maxTokens: 16384,
      multimodal: true,
      supportsReasoning: false,
    },
    OPENAI_GPT_4_1: {
      id: 'gpt-4.1',
      name: 'GPT-4.1',
      contextWindow: 1047576,
      maxTokens: 32768,
      multimodal: true,
      supportsReasoning: false,
      supportFunctionCalling: true,
    },
    OPENAI_GPT_4_5_PREVIEW: {
      id: 'gpt-4.5-preview',
      name: 'GPT-4.5 Preview',
      contextWindow: 128000,
      maxTokens: 16384,
      multimodal: true,
      supportsReasoning: false,
      supportFunctionCalling: true,
    }
  },
  google: {
    GEMINI_2_5_PRO: {
      id: 'gemini-2.5-pro',
      name: 'Gemini 2.5 Pro',
      contextWindow: 1048576,
      maxTokens: 65536,
      multimodal: true,
      supportFunctionCalling: true,
      supportsReasoning: true,
      reasoningParameters: {
        type: 'budget',
        budgetTokenLimit: 32768,
        budgetTokens: 4096,
      },
    },
    GEMINI_2_5_FLASH:{
      id: 'gemini-2.5-flash',
      name: 'Gemini 2.5 Flash',
      contextWindow: 1048576,
      maxTokens: 65536,
      multimodal: true,
      supportFunctionCalling: true,
      supportsReasoning: true,
      reasoningParameters: {
        type: 'budget',
        budgetTokenLimit: 24576,
        budgetTokens: 4096,
      },
    },
    GEMINI_2_5_FLASH_LITE:{
      id: 'gemini-2.5-flash-lite',
      name: 'Gemini 2.5 Flash Lite',
      contextWindow: 1048576,
      maxTokens: 65536,
      multimodal: true,
      supportFunctionCalling: true,
      supportsReasoning: true,
      reasoningParameters: {
        type: 'budget',
        budgetTokenLimit: 24576,
        budgetTokens: 4096,
      },
    },
    GEMINI_2_5_FLASH_IMAGE_PREVIEW: {
      id: 'gemini-2.5-flash-image-preview',
      name: 'Gemini 2.5 Flash Image Preview',
      contextWindow: 32768,
      maxTokens: 32768,
      multimodal: true,
      imageGeneration: true,
      supportFunctionCalling: false,
      supportsReasoning: false,
    },
    GEMINI_2_0_FLASH: {
      id: 'gemini-2.0-flash',
      name: 'Gemini 2.0 Flash',
      contextWindow: 1048576,
      maxTokens: 8192,
      multimodal: true,
      supportFunctionCalling: true,
      supportsReasoning: false,
    }
  },
  xai: {
    XAI_GROK_4: {
      id: 'grok-4-latest',
      name: 'Grok 4',
      contextWindow: 256000,
      maxTokens: 131072,
      multimodal: false,
      supportFunctionCalling: true,
      supportsReasoning: true,
      reasoningParameters: {
        type: 'effort',
        effort: 'high',
      },
    },
    XAI_GROK_CODE_FAST_1: {
      id: 'grok-code-fast-1',
      name: 'Grok Code Fast 1',
      contextWindow: 256000,
      maxTokens: 131072,
      multimodal: false,
      supportFunctionCalling: true,
      supportsReasoning: true,
      reasoningParameters: {
        type: 'effort',
        effort: 'high',
      },
    },
    XAI_GROK_3_MINI_BETA: {
      id: 'grok-3-mini-beta',
      name: 'Grok 3 Mini Beta',
      contextWindow: 131072,
      maxTokens: 131072,
      multimodal: false,
      supportFunctionCalling: true,
      supportsReasoning: true,
      reasoningParameters: {
        type: 'effort',
        effort: 'high',
      },
    },
    XAI_GROK_3_BETA: {
      id: 'grok-3-beta',
      name: 'Grok 3 Beta',
      contextWindow: 131072,
      maxTokens: 131072,
      multimodal: false,
      supportFunctionCalling: true,
      supportsReasoning: false,
    },
    XAI_GROK_3_MINI_FAST_BETA: {
      id: 'grok-3-mini-fast-beta',
      name: 'Grok 3 Mini Fast Beta',
      contextWindow: 131072,
      maxTokens: 131072,
      multimodal: false,
      supportFunctionCalling: true,
      supportsReasoning: true,
      reasoningParameters: {
        type: 'effort',
        effort: 'high',
      },
    },
    XAI_GROK_3_FAST_BETA: {
      id: 'grok-3-fast-beta',
      name: 'Grok 3 Fast Beta',
      contextWindow: 131072,
      maxTokens: 131072,
      multimodal: false,
      supportFunctionCalling: true,
      supportsReasoning: false,
    },
  },
  openrouter: {
  },
};