"""add_mcp_settings_to_user_settings

Revision ID: 3903bc07b587
Revises: f7d73032b202
Create Date: 2025-04-22 13:58:53.739060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3903bc07b587'
down_revision: Union[str, None] = 'f7d73032b202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('mcp_servers_config_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('user_settings', sa.Column('disabled_mcp_servers', sa.JSON(), nullable=True))
    op.add_column('user_settings', sa.Column('disabled_mcp_tools', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'disabled_mcp_tools')
    op.drop_column('user_settings', 'disabled_mcp_servers')
    op.drop_column('user_settings', 'mcp_servers_config_encrypted')
    # ### end Alembic commands ###
