"""Create user and user_settings tables (revised)

Revision ID: f7d73032b202
Revises: 
Create Date: 2025-04-16 00:34:34.264359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d73032b202'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_keys_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('default_temperature', sa.Float(), nullable=True),
    sa.Column('default_max_tokens', sa.Integer(), nullable=True),
    sa.Column('default_vendor', sa.String(), nullable=True),
    sa.Column('default_model', sa.String(), nullable=True),
    sa.Column('default_reasoning_effort', sa.String(), nullable=True),
    sa.Column('default_web_search', sa.Boolean(), nullable=True),
    sa.Column('openrouter_models', sa.JSON(), nullable=True),
    sa.Column('title_generation_vendor', sa.String(), nullable=True),
    sa.Column('title_generation_model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
